### ISSUE TITLE
Error "jQuery requires a window with a document"

### ISSUE THREAD

**Issue by alfredbrown9847** [davidcana/ZPT-JS#1]
Hello.
I was trying to make a basic test of ZPT-JS in NodeJS, using for that the "jsdom" package,
but it fails with the "jQuery requires a window with a document" error.
Please, could you publish in the wiki an example of a running code of ZPT-JS working in NodeJS?
Thanks in advance.

**Comment by davidcana** [comment]
Hello! Thanks for reporting this issue!
I wrote ZPT-JS thinking in a browser environment, so I didn't test in NodeJS. It failed with that error, you are right. To solve this issue you must use node-jsdom package. Take a look at https://github.com/davidcana/ZPT-JS/wiki/Using-ZPT-JS for more details.
Sorry for the delay!
